-- 1) Tablespace de datos 'Esquema' con dos datafiles autoextendibles
CREATE TABLESPACE Esquema
  DATAFILE 'C:\app\USER\product\21c\oradata\XE\tESQUEMA01.dbf' SIZE 5M
      AUTOEXTEND ON NEXT 1M MAXSIZE 10M,
    'C:\app\USER\product\21c\oradata\XE\tSQUEMA02.dbf'  SIZE 5M
      AUTOEXTEND ON NEXT 1M MAXSIZE 10M
  EXTENT MANAGEMENT LOCAL
  SEGMENT SPACE MANAGEMENT AUTO
  
--2 Crear un Tablespace temporal
CREATE TEMPORARY TABLESPACE temp_esquema
TEMPFILE 'C:\app\USER\product\21c\oradata\XE\ESQUEMA01temp.dbf'
SIZE 10M
EXTENT MANAGEMENT LOCAL;

--3. CREAR EL ESQUEMA PARA LA  UNMSM
-- 3.1) Tabla PERSONA (datos comunes)
CREATE TABLE persona (
  persona_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre       VARCHAR2(60) NOT NULL,
  apellido1    VARCHAR2(60) NOT NULL,
  apellido2    VARCHAR2(60),
  direccion    VARCHAR2(200) NOT NULL,
  telefono     VARCHAR2(30) NOT NULL,
  email        VARCHAR2(150) NOT NULL,
  CONSTRAINT pk_persona PRIMARY KEY (persona_id),
  CONSTRAINT uq_persona_email UNIQUE (email),
  -- Restricción simple: email debe tener al menos 5 caracteres
  CONSTRAINT ck_persona_email_len CHECK (LENGTH(email) >= 5),
  -- Restricción simple: teléfono debe tener mínimo 6 caracteres
  CONSTRAINT ck_persona_telefono_len CHECK (LENGTH(telefono) >= 6)
) TABLESPACE USERS;


-- 3.2) Tabla PROFESOR (1:1 con PERSONA)
CREATE TABLE profesor (
  persona_id NUMBER,
  departamento VARCHAR2(100) NOT NULL,
  dedicacion   VARCHAR2(40) NOT NULL,
  CONSTRAINT pk_profesor PRIMARY KEY (persona_id),
  CONSTRAINT fk_profesor_persona FOREIGN KEY (persona_id)
    REFERENCES persona(persona_id) ON DELETE CASCADE
) TABLESPACE Esquema;

-- 3.3) Tabla CENTRO (centros donde se imparten clases)
CREATE TABLE centro (
  centro_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre    VARCHAR2(120) NOT NULL,
  direccion VARCHAR2(200),
  CONSTRAINT pk_centro PRIMARY KEY (centro_id)
) TABLESPACE Esquema;

-- 3.4) Tabla relacion Profesor <-> Centro (N:N)
CREATE TABLE profesor_centro (
  profesor_persona_id NUMBER NOT NULL,
  centro_id           NUMBER NOT NULL,
  CONSTRAINT pk_profesor_centro PRIMARY KEY (profesor_persona_id, centro_id),
  CONSTRAINT fk_pc_profesor FOREIGN KEY (profesor_persona_id)
    REFERENCES profesor(persona_id) ON DELETE CASCADE,
  CONSTRAINT fk_pc_centro FOREIGN KEY (centro_id)
    REFERENCES centro(centro_id) ON DELETE CASCADE
) TABLESPACE Esquema;

-- 3.5) Tabla ALUMNO
CREATE TABLE alumno (
  persona_id   NUMBER,
  centro_id    NUMBER NOT NULL,   -- el alumno está matriculado en un único centro
  expediente_no VARCHAR2(30) NOT NULL,
  titulacion    VARCHAR2(150) NOT NULL,
  CONSTRAINT pk_alumno PRIMARY KEY (persona_id),
  CONSTRAINT fk_alumno_persona FOREIGN KEY (persona_id)
    REFERENCES persona(persona_id) ON DELETE CASCADE,
  CONSTRAINT fk_alumno_centro FOREIGN KEY (centro_id)
    REFERENCES centro(centro_id),
  CONSTRAINT uq_alumno_expediente UNIQUE (expediente_no)
) TABLESPACE Esquema;

-- 3.6) Tabla PERSONAL (personal administrativo)
CREATE TABLE personal (
  persona_id NUMBER,
  unidad_administrativa VARCHAR2(120) NOT NULL,
  categoria_profesional VARCHAR2(80) NOT NULL,
  CONSTRAINT pk_personal PRIMARY KEY (persona_id),
  CONSTRAINT fk_personal_persona FOREIGN KEY (persona_id)
    REFERENCES persona(persona_id) ON DELETE CASCADE
) TABLESPACE Esquema;


--CREACION DE VISTAS
-- 4.1) vista auxiliar: centros por profesor (agrega nombres)
CREATE OR REPLACE VIEW vw_centros_profesor AS
SELECT pc.profesor_persona_id AS persona_id,
       LISTAGG(c.nombre, ', ') WITHIN GROUP (ORDER BY c.nombre) AS centros
FROM profesor_centro pc
JOIN centro c ON pc.centro_id = c.centro_id
GROUP BY pc.profesor_persona_id;

-- 4.2) vista principal de miembros con datos comunes y particulares
CREATE OR REPLACE VIEW v_miembros_universidad AS
SELECT
  p.persona_id,
  RTRIM(p.nombre || ' ' || p.apellido1 || ' ' || NVL(p.apellido2,'')) AS nombre_completo,
  p.direccion,
  p.telefono,
  p.email,
  CASE
    WHEN pr.persona_id IS NOT NULL THEN 'PROFESOR'
    WHEN al.persona_id IS NOT NULL THEN 'ALUMNO'
    WHEN pe.persona_id IS NOT NULL THEN 'PERSONAL'
    ELSE 'OTRO'
  END AS tipo_vinculo,
  pr.departamento,
  pr.dedicacion,
  vc.centros,
  al.expediente_no,
  al.titulacion,
  pe.unidad_administrativa,
  pe.categoria_profesional
FROM persona p
LEFT JOIN profesor pr ON p.persona_id = pr.persona_id
LEFT JOIN vw_centros_profesor vc ON p.persona_id = vc.persona_id
LEFT JOIN alumno al ON p.persona_id = al.persona_id
LEFT JOIN personal pe ON p.persona_id = pe.persona_id
-- opcional: filtrar sólo los que tienen vínculo con la universidad:
WHERE pr.persona_id IS NOT NULL OR al.persona_id IS NOT NULL OR pe.persona_id IS NOT NULL;

SELECT * FROM v_miembros_universidad
ORDER BY nombre_completo;

--5. Crear índices para buscar por nombre (profesor, alumno y personal)
-- Índice funcional sobre nombre completo (case-insensitive)
CREATE INDEX idx_persona_nombre ON persona (UPPER(nombre || ' ' || apellido1 || ' ' || NVL(apellido2,''))) TABLESPACE Esquema;

-- Índices para acelerar JOINs / búsquedas por rol (si no existen)
CREATE INDEX idx_profesor_persona ON profesor (persona_id) TABLESPACE Esquema;
CREATE INDEX idx_alumno_persona  ON alumno (persona_id) TABLESPACE Esquema;
CREATE INDEX idx_personal_persona ON personal (persona_id) TABLESPACE Esquema;

--6. Comprobaciones ÚTILES
-- comprobar datafiles del tablespace Esquema
SELECT tablespace_name, file_name, bytes/1024/1024 AS MB
FROM dba_data_files
WHERE tablespace_name = 'ESQUEMA';

-- comprobar tempfiles del TempEsquema
SELECT tablespace_name, file_name, bytes/1024/1024 AS MB
FROM dba_temp_files
WHERE tablespace_name = 'temp_esquema';




